# Generated by Django 3.2.9 on 2021-12-01 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='To do', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('time_required', models.DurationField(blank=True, null=True)),
                ('energy_required', models.CharField(blank=True, choices=[('lo', 'Low'), ('md', 'Medium'), ('hi', 'High'), ('no', 'None')], default='no', max_length=2)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('inbox', 'Inbox'), ('next', 'Next'), ('wait', 'Waiting'), ('sched', 'Scheduled'), ('smday', 'Someday')], default='inbox', max_length=5)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.tag')),
            ],
            bases=('todo.tag',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.tag')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('todo.tag',),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.tag')),
            ],
            bases=('todo.tag',),
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.action')),
                ('scheduled_for', models.DateTimeField()),
            ],
            bases=('todo.action',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Project Name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, max_length=50)),
                ('next_action', models.CharField(blank=True, choices=[('PA', 'Parallel'), ('SE', 'Sequential')], default='PA', max_length=2)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(blank=True, to='todo.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todo.Tag'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
