# Generated by Django 3.2.9 on 2021-12-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_focused',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_focused',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
